In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df2 = pd.read_pickle("cleanDataBase.pkl")
df2

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Location
0,20,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)"
1,24,0,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)"
2,22,1,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,"(12.9551, 77.6593)"
3,22,0,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,"(12.9473, 77.5616)"
4,22,1,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,0,Single,Student,No Income,Post Graduate,2,Regular,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)"
384,23,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9854,77.7081,560048,Yes,Positive,"(12.9854, 77.7081)"
385,22,0,Single,Student,No Income,Post Graduate,5,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)"
386,23,1,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)"
387,23,1,Single,Student,No Income,Post Graduate,5,Frequent,12.8988,77.5764,560078,Yes,Positive,"(12.8988, 77.5764)"

# Geography Analysis

In [3]:
%pip install geopy pandas

Requirement already satisfied: geopy in C:\Users\jorge\Bibiana\Lib\site-packages (2.5.0)
Requirement already satisfied: pandas in C:\Users\jorge\Bibiana\Lib\site-packages (3.0.3)
Requirement already satisfied: geographiclib<3,>=1.52 in C:\Users\jorge\Bibiana\Lib\site-packages (from geopy) (2.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\jorge\Bibiana\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jorge\Bibiana\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\jorge\Bibiana\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jorge\Bibiana\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [7]:
%pip install reverse_geocoder pandas

Requirement already satisfied: reverse_geocoder in C:\Users\jorge\Bibiana\Lib\site-packages (1.5.1)
Requirement already satisfied: pandas in C:\Users\jorge\Bibiana\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.11.0 in C:\Users\jorge\Bibiana\Lib\site-packages (from reverse_geocoder) (2.4.6)
Requirement already satisfied: scipy>=0.17.1 in C:\Users\jorge\Bibiana\Lib\site-packages (from reverse_geocoder) (1.18.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jorge\Bibiana\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\jorge\Bibiana\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jorge\Bibiana\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import reverse_geocoder as rg

In [8]:
#coordinates = [ast.literal_eval(str('Location')) for celda in dftest['tu_columna_de_coordenadas']]
coordinates = list(zip(df2 ['latitude'],df2['longitude']))
place = rg.search(coordinates)
df2 ['City'] = [x['name'] for x in place]
df2 ['Country'] = [x['cc'] for x in place]
df2

Loading formatted geocoded file...

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Location,City,Country
0,20,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)",Bangalore,IN
1,24,0,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)",Bangalore,IN
2,22,1,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,"(12.9551, 77.6593)",Bangalore,IN
3,22,0,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,"(12.9473, 77.5616)",Bangalore,IN
4,22,1,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)",Bangalore,IN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,0,Single,Student,No Income,Post Graduate,2,Regular,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)",Bangalore,IN
384,23,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9854,77.7081,560048,Yes,Positive,"(12.9854, 77.7081)",Bangalore,IN
385,22,0,Single,Student,No Income,Post Graduate,5,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)",Bangalore,IN
386,23,1,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)",Bangalore,IN
387,23,1,Single,Student,No Income,Post Graduate,5,Frequent,12.8988,77.5764,560078,Yes,Positive,"(12.8988, 77.5764)",Bangalore,IN

In [12]:
df2[['City','Country']].nunique()

City       4
Country    1
dtype: int64

In [13]:
df2['City'].value_counts()

City
Bangalore      343
Yelahanka       30
Hoskote         14
Nelamangala      1
Name: count, dtype: int64

In [14]:
df2 ['Province'] = [x['admin1'] for x in place]
df2

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Location,City,Country,Province
0,20,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)",Bangalore,IN,Karnataka
1,24,0,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)",Bangalore,IN,Karnataka
2,22,1,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,"(12.9551, 77.6593)",Bangalore,IN,Karnataka
3,22,0,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,"(12.9473, 77.5616)",Bangalore,IN,Karnataka
4,22,1,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)",Bangalore,IN,Karnataka
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,0,Single,Student,No Income,Post Graduate,2,Regular,12.9766,77.5993,560001,Yes,Positive,"(12.9766, 77.5993)",Bangalore,IN,Karnataka
384,23,0,Single,Student,No Income,Post Graduate,4,Frequent,12.9854,77.7081,560048,Yes,Positive,"(12.9854, 77.7081)",Bangalore,IN,Karnataka
385,22,0,Single,Student,No Income,Post Graduate,5,Frequent,12.9850,77.5533,560010,Yes,Positive,"(12.985, 77.5533)",Bangalore,IN,Karnataka
386,23,1,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,"(12.977, 77.5773)",Bangalore,IN,Karnataka
387,23,1,Single,Student,No Income,Post Graduate,5,Frequent,12.8988,77.5764,560078,Yes,Positive,"(12.8988, 77.5764)",Bangalore,IN,Karnataka

In [15]:
df2['Province'].nunique()
df2['Province'].value_counts()

Province
Karnataka    388
Name: count, dtype: int64

In [16]:
import tkinter as tk
from tkinter import messagebox